services:
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./wetty-chat-mobile/www:/usr/share/nginx/html:ro # cd wetty-chat-mobile && npm ci && npm run build
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  postgres:
    restart: unless-stopped
    image: postgres:18-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: wetty_chat
      POSTGRES_PASSWORD: NIM1gs7unjbQumYD
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    restart: unless-stopped
    build: backend
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://wetty_chat:NIM1gs7unjbQumYD@postgres:5432/wetty_chat
  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: "rustfsadmin"
      RUSTFS_SECRET_KEY: "rustfsadmin"
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_REGION: "us-west-2"
    command: /data --console-enable --address ":9000"
  init-rustfs:
    image: minio/mc:latest
    depends_on:
      - rustfs
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for RustFS to start...';
      sleep 3;
      mc alias set myrustfs http://rustfs:9000 rustfsadmin rustfsadmin;
      mc mb myrustfs/wetty-chat-local-dev --ignore-existing;
      mc anonymous set download myrustfs/wetty-chat-local-dev;
      echo 'Bucket created and set to public!';
      exit 0;
      "
volumes:
  postgres_data: