default_platform(:ios)

platform :ios do
  desc "Sync development signing"
  lane :sync_dev_signing do
    match(
      type: "development",
      git_url: "git@github.com:Codetector1374/apple_developer_certs.git",
      readonly: true
    )
  end
end
