name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.2
  flutter_svg: ^2.2.0
  http: ^1.6.0
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  url_launcher: ^6.2.0
  shared_preferences: ^2.2.0
  scrollable_positioned_list: ^0.3.8
  web_socket_channel: ^3.0.3
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MiSans
      fonts:
        - asset: MiSans/MiSans/ttf/MiSans-Thin.ttf
          weight: 100
        - asset: MiSans/MiSans/ttf/MiSans-ExtraLight.ttf
          weight: 200
        - asset: MiSans/MiSans/ttf/MiSans-Light.ttf
          weight: 300
        - asset: MiSans/MiSans/ttf/MiSans-Regular.ttf
          weight: 400
        - asset: MiSans/MiSans/ttf/MiSans-Medium.ttf
          weight: 500
        - asset: MiSans/MiSans/ttf/MiSans-Demibold.ttf
          weight: 600
        - asset: MiSans/MiSans/ttf/MiSans-Bold.ttf
          weight: 700
        - asset: MiSans/MiSans/ttf/MiSans-Heavy.ttf
          weight: 800
